(define (integral f a b n)
  (define h (/ (- b a) n))
  (define (next k) (+ k 1))
  (define (term k)
    (define (fx k) (f (+ a (* k h))))
    (cond ((or (= 0 k) (= n k)) (fx k))
          ((even? k) (* 2 (fx k)))
          (else (* 4 (fx k)))))
  (define (sum term k next)
    (if (> k n)
      0
      (+ (term k)
         (sum term (next k) next))))
  (* (/ h 3) (sum term 0 next)))
